# SYSMAINT Helm Chart - ServiceAccount Template
#
# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Harery

{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sysmaint.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sysmaint.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
